ci: ignore success pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,16 +59,16 @@ jobs:
   #     - name: Test coverage
   #       run: npm run test:coverage
 
-  ci-success:
-    name: CI Success
-    runs-on: ubuntu-latest
-    needs: [style]
-    if: always()
+  # ci-success:
+  #   name: CI Success
+  #   runs-on: ubuntu-latest
+  #   needs: [style]
+  #   if: always()
 
-    steps:
-      - name: Check all jobs
-        run: |
-          if [[ "${{ needs.style.result }}" != "success" ]] || [[ "${{ needs.test.result }}" != "success" ]]; then
-            echo "One or more jobs failed"
-            exit 1
-          fi
+  #   steps:
+  #     - name: Check all jobs
+  #       run: |
+  #         if [[ "${{ needs.style.result }}" != "success" ]] || [[ "${{ needs.test.result }}" != "success" ]]; then
+  #           echo "One or more jobs failed"
+  #           exit 1
+  #         fi
